name: fastapi-canciones

services: 
  fastapi-app:  
    build:  
      context: .  
      dockerfile: Dockerfile  
    container_name: fastapi-app-canciones 
    restart: always  
    ports:  
      - "8000:8000"  
    depends_on:  
      - fastapi-db  
  fastapi-db:  
    image: postgres:latest
    container_name: fastapi-db-canciones
    environment:  
      POSTGRES_ROOT_PASSWORD: ${POSTGRES_ROOT_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:  
      - "5432:5432"  
  